# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 20 Jan 2016 14:43:00 +0000
*               @ALL          1
*               @user         8
