<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Wed, 20 Jan 2016 16:26:04 +0100
 */

$conf['title'] = 'AppFM Wiki';
$conf['template'] = 'codowik';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['plugin']['indexmenu']['page_index'] = '{{indexmenu>..#1|js#thread navbar max#3#2 tsort msort}}';

// end auto-generated content
